    - name: Download MySQL Repository 
      get_url:
         url: https://dev.mysql.com/get/mysql-apt-config_0.8.20-1_all.deb
         dest: /home/nanditasahu031
      become: yes

    - name: Add MySQL Repository
      apt: 
         deb: ./mysql-apt-config_0.8.20-1_all.deb
      become: yes 

    - name: Install and Configure Database
      apt: name='{{ item }}' state=present
      become: yes
      loop:
      - python3-mysqldb
      - mysql-server
      - mysql-client


    - name: Start Database Service
      service: 
        name: mysql 
        state: started
        enabled: yes

    - name: Create Application Database
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock 
        name: 'employee_db'
        state: present
      become: yes

    - name: Create Database User with grant option
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: db_user
        password: 'Passw0rd'
        priv: "*.*:ALL"
        state: present
      become: yes